/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ScheduleSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'date',
    'id',
    'lastFetchedAt',
    'payload',
    'theaterId',
    'updatedAt',
  ] as const
  $columns = ScheduleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastFetchedAt: DateTime
  @column()
  declare payload: any
  @column()
  declare theaterId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TheaterSchema extends BaseModel {
  static $columns = [
    'allocineId',
    'createdAt',
    'id',
    'isActive',
    'name',
    'slug',
    'updatedAt',
  ] as const
  $columns = TheaterSchema.$columns
  @column()
  declare allocineId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
